name: tabletours
favicon: null
layout_spectrum: 0.9063967214897275
typography_spectrum: 0.538944392465055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c9c5ba'
    - '#b48503'
    - '#0e0000'
    - '#737685'
    - '#c2382b'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
