name: tabletours
favicon: null
layout_spectrum: 0.9063967214897275
typography_spectrum: 0.538944392465055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b1a89f'
    - '#18161b'
    - '#c60814'
    - '#406ebe'
  brandStrength: 0.375
  lightness: 0.4839263709727675
  saturation: 0.7064304675441235
  rhythmicContrast: 0.5640010512433946
purpose: []
